---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
spec:
  storageClassName: "csi-ceph-ssd-ms1"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
