---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
      - image: redmine:4.1.1
        name: redmine
        env:
        - name: REDMINE_DB_POSTGRES
          value: database
        - name: REDMINE_DB_USERNAME
          value: testuser
        - name: REDMINE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgeres-secret
              key: password
        - name: REDMINE_DB_DATABASE
          value: testdatabase
        - name: REDMINE_SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: redmine-secret
              key: super-secret
        ports:
        - containerPort: 3000
          protocol: TCP
